apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 11.1.2
deprecated: false
description: The easiest way to run WireGuard VPN + Web-based Admin UI.
home: https://truecharts.org/charts/stable/wg-easy
icon: https://truecharts.org/img/hotlink-ok/chart-icons/wg-easy.png
keywords:
  - wg-easy
  - wireguard
  - weejewel
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: wg-easy
sources:
  - https://github.com/zach-snell/charts/tree/main/charts/stable/wg-easy
  - https://ghcr.io/zach-snell/wg-easy
  - https://github.com/zach-snell/wg-easy
type: application
version: 3.0.8
annotations:
  truecharts.org/catagories: |
    - networking
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
